version: "3.7"

services:

  products:
    build: 
      context: ../src
      dockerfile: Dockerfile
    container_name: products
    ports:
      - '5000:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      
  mongodb:
    image: mongo:4
    container_name: mongodb
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo:
    driver: local